import { AlignmentChar } from "../../SequenceAlignmentPlot"
import { TreeItem } from "..";
import data241 from "./241_mammals_treedata.json";
import speciesData from "./species_metadata.json";

export const ORDERS = [
  "PRIMATES",
  "DERMOPTERA",
  "CARNIVORA",
  "LAGOMORPHA",
  "CETARTIODACTYLA",
  "RODENTIA",
  "HYRACOIDEA",
  "PERISSODACTYLA",
  "CHIROPTERA",
  "EULIPOTYPHLA",
  "PHOLIDOTA",
  "PILOSA",
  "AFROSORICIDA",
  "SIRENIA",
  "TUBULIDENTATA",
  "PROBOSCIDEA",
  "SCANDENTIA",
  "CINGULATA",
  "MACROSCELIDEA",
] as const;

type Order = (typeof ORDERS)[number];

export type SpeciesRow = {
  id: string;
  displayName: string;
  order: string;
  coverage: number;
};

export interface SpeciesMeta {
  displayName: string;
  order: Order;
  primateGroup: string | null;
  colorGroup: string;
  distToHuman: number;
  colorLabel: string;
}

export const SPECIES_META: Record<string, SpeciesMeta> = Object.fromEntries(
  speciesData.map((s) => [
    s.species,
    {
      displayName: s.common_name,
      order: s.order as Order,
      primateGroup: s.primate_group,
      colorGroup: s.color_group,
      distToHuman: s.dist_to_human,
      colorLabel: s.color_label,
    },
  ])
);

export const SPECIES_ORDER_IN_API_RETURN: string[] = speciesData.map((s) => s.species);

// Colors generated by https://medialab.github.io/iwanthue/ with H 0-360, C 30-80, L 25-70
// Primate subgroup colors use the green spectrum previously occupied by the single PRIMATES entry.
const COLOR_GROUP_COLORS: Record<string, string> = {
  // Primate subgroups
  GREAT_APES: "#114a38",
  GIBBONS: "#006b30",
  OLD_WORLD_MONKEYS: "#1a6b5e",
  NEW_WORLD_MONKEYS: "#3a7a00",
  STREPSIRRHINI: "#4d5e00",
  // Non-primate orders (color_group === order for these)
  CINGULATA: "#68003b",
  PILOSA: "#2b1924",
  PROBOSCIDEA: "#9f006d",
  SIRENIA: "#ff46c6",
  HYRACOIDEA: "#9c00b6",
  TUBULIDENTATA: "#00356c",
  MACROSCELIDEA: "#4b95fe",
  AFROSORICIDA: "#016aae",
  SCANDENTIA: "#569cc8",
  DERMOPTERA: "#006c6c",
  LAGOMORPHA: "#006e22",
  RODENTIA: "#756a53",
  EULIPOTYPHLA: "#5d4500",
  CHIROPTERA: "#c68300",
  PERISSODACTYLA: "#ea6e00",
  PHOLIDOTA: "#cd5a12",
  CARNIVORA: "#b81212",
  CETARTIODACTYLA: "#97495f",
};

export const getLabel = (id: string) => {
  return SPECIES_META[id]?.displayName ?? id;
};

export const getOrder = (id: string) => {
  return SPECIES_META[id]?.order ?? null;
};

export const getColorGroup = (id: string) => {
  return SPECIES_META[id]?.colorGroup ?? null;
};

export const getColor = (id: string) => {
  const colorGroup = getColorGroup(id);
  return COLOR_GROUP_COLORS[colorGroup ?? ""] ?? "";
};

export const getPrimateGroup = (id: string) => {
  return SPECIES_META[id]?.primateGroup ?? null;
};

export const getDistToHuman = (id: string) => {
  return SPECIES_META[id]?.distToHuman ?? null;
};

export const getColorLabel = (id: string) => {
  return SPECIES_META[id]?.colorLabel ?? null;
};

type TestDataNode = { name: string; branch_length: number | null; children?: TestDataNode[] };

export const formatNode = (node: TestDataNode): TreeItem => {
  const newNode: TreeItem = { id: node.name, branch_length: node.branch_length };

  if (node.children) {
    const newChildren = node.children.map((child) => formatNode(child));
    newNode.children = newChildren;
  }

  return newNode;
};

const numberToNucleotide = new Map<number, AlignmentChar>([
  [0, "*"],
  [1, "A"],
  [2, "C"],
  [3, "G"],
  [4, "T"],
  [5, "N"],
  [6, "M"],
  [7, "-"]
]);

/**
 * Takes sequences (numbers 0-7) and a matching ordered array to map each sequence to a species,
 * and produces data for the SequenceAlignmentPlot
 */
export const makeAlignmentPlotData = (
  sequences: number[][],
  /**
   * order of species in `sequences`
   */
  speciesOrder: string[]
): { [species: string]: AlignmentChar[] } => {
  if (sequences.length !== speciesOrder.length) {
    throw new Error("Number of sequences doesn't match number of species");
  }

  const mappedSequence: { [species: string]: AlignmentChar[] } = {};
  sequences.forEach((sequence, i) => {
    const species = speciesOrder[i];
    mappedSequence[species] = sequence.map((num) => numberToNucleotide.get(num) ?? "-");
  });
  return mappedSequence;
};

export const phyloTreeRoot = formatNode(data241);

export const allSpecies = new Set(SPECIES_ORDER_IN_API_RETURN);
