import * as React from "react";
import { Meta, StoryObj } from "@storybook/react-vite";
import { LicenseInfo } from "@mui/x-license";
import { BiosampleTable, initialTableState } from "./BiosampleTable";
import { allColsHidden, rnaSeqCheckCol } from "./columns";
import { EncodeBiosample } from "./types";
import { Stack } from "@mui/material";
import { DataGridPremiumProps, gridVisibleRowsSelector, isAutogeneratedRow, useGridApiRef } from "@mui/x-data-grid-premium";

const meta = {
  title: "ui-components/BiosampleTable",
  component: BiosampleTable,
  tags: ["autodocs"],
  parameters: {
    controls: { expanded: true },
  },
  decorators: [
    (Story) => {
      LicenseInfo.setLicenseKey(process.env.NEXT_PUBLIC_MUI_X_LICENSE_KEY as string);
      return <Story />;
    },
  ],
} satisfies Meta<typeof BiosampleTable>;

export default meta;
type Story = StoryObj<typeof BiosampleTable>;

export const Human: Story = {
  render: () => {
    return <BiosampleTable assembly="GRCh38" divHeight={{ height: 600 }} />;
  },
};

export const Mouse: Story = {
  render: () => {
    return <BiosampleTable assembly="mm10" divHeight={{ height: 600 }} />;
  },
};

export const ByCellAndTissueDownloads: Story = {
  render: () => {
    const overrideInitialTableState = {
      ...initialTableState,
      columns: {
        columnVisibilityModel: {
          ...allColsHidden,
          ontology: true,
          bedurl: true,
        },
      },
    };

    const apiRef = useGridApiRef();

    React.useEffect(() => {
      return apiRef.current?.subscribeEvent("rowExpansionChange", (params, event, details) => {
        const leavesAreVisible = Boolean(
          gridVisibleRowsSelector(apiRef).rows.filter((row) => !isAutogeneratedRow(row.model)).length
        );
        const currentVisibilityModel = details.api.state.columns.columnVisibilityModel;
        if (leavesAreVisible) {
          details.api.setColumnVisibilityModel({
            ...currentVisibilityModel,
            assays: true,
            dnaseZ: true,
            atacZ: true,
            h3k4me3Z: true,
            h3k27ac: true,
            ctcfZ: true,
          });
        } else {
          details.api.setColumnVisibilityModel({
            ...currentVisibilityModel,
            assays: false,
            dnaseZ: false,
            atacZ: false,
            h3k4me3Z: false,
            h3k27ac: false,
            ctcfZ: false,
          });
        }
      });
    }, [apiRef]);

    return (
      <BiosampleTable
        apiRef={apiRef}
        assembly="GRCh38"
        divHeight={{ height: 600 }}
        initialState={overrideInitialTableState}
        slotProps={{ toolbar: { csvOptions: { allColumns: true }, excelOptions: { allColumns: true } } }}
      />
    );
  },
};

export const ShowRnaSeq: Story = {
  render: () => {
    return (
      <BiosampleTable
        assembly="GRCh38"
        divHeight={{ height: 600 }}
        initialState={{
          ...initialTableState,
          columns: {
            columnVisibilityModel: { ...initialTableState.columns.columnVisibilityModel, [rnaSeqCheckCol.field]: true },
          },
        }}
        onRowClick={(params) => console.log(params.row)}
      />
    );
  },
};

export const MultiSelectWithCheckboxes: Story = {
  render: () => {
    const [selected, setSelected] = React.useState<EncodeBiosample[]>([]);

    return (
      <Stack>
        <BiosampleTable
          assembly="GRCh38"
          divHeight={{ height: 600 }}
          checkboxSelection
          onSelectionChange={(newSelected) => setSelected(newSelected)}
        />
        Selected:
        {selected.map((x) => <span key={x.name}>{x.name}</span>)}
      </Stack>
    );
  },
};

export const SingleSelectWithoutCheckboxes: Story = {
  render: () => {
    const [selected, setSelected] = React.useState<EncodeBiosample[]>([]);

    return (
      <Stack>
        <BiosampleTable
          assembly="GRCh38"
          divHeight={{ height: 600 }}
          disableRowSelectionOnClick={false}
          disableMultipleRowSelection
          onSelectionChange={(newSelected) => setSelected(newSelected)}
          isRowSelectable={(params) => !isAutogeneratedRow(params.row)}
        />
        Selected:
        {selected.map((x) => <span key={x.name}>{x.name}</span>)}
      </Stack>
    );
  },
};