import {
  GridColDef,
  GridComparatorFn,
  gridRowIdSelector,
  gridRowNodeSelector,
  gridRowSelector,
  isAutogeneratedRow,
} from "@mui/x-data-grid-premium";
import { AssayWheel } from "./AssayWheel";
import { CcreAssay, EncodeBiosample } from "./types";
import { DownloadButton } from "./DownloadButton";
import { AggregateDownloadButton, getAvailableFiles } from "./AggregateDownload";
import { capitalize, Stack, Tooltip } from "@mui/material";
import { Check, InfoOutline } from "@mui/icons-material";

/**
 * @todo at some point, instead of checking for is rowNode.type === "group", can use isAutogeneratedRow instead
 */

export const ontologyCol: GridColDef<EncodeBiosample> = {
  field: "ontology",
  headerName: "Organ/Tissue",
  type: "singleSelect",
  valueOptions: [
    "adipose",
    "adrenal gland",
    "blood",
    "blood vessel",
    "bone",
    "bone marrow",
    "brain",
    "breast",
    "connective tissue",
    "embryo",
    "epithelium",
    "esophagus",
    "eye",
    "fallopian tube",
    "gallbladder",
    "heart",
    "kidney",
    "large intestine",
    "limb",
    "liver",
    "lung",
    "lymphoid tissue",
    "mouth",
    "muscle",
    "nerve",
    "nose",
    "ovary",
    "pancreas",
    "paraythroid gland",
    "penis",
    "placenta",
    "prostate",
    "skin",
    "small intestine",
    "spinal cord",
    "spleen",
    "stomach",
    "testis",
    "thymus",
    "thyroid",
    "urinary bladder",
    "uterus",
    "vagina",
  ],
  valueFormatter: (value) => value && capitalize(value),
};

export const displayNameCol: GridColDef<EncodeBiosample> = {
  field: "displayname",
  headerName: "Biosample",
  valueFormatter: (value) => value && capitalize(value),
  maxWidth: 300,
};

export const sampleTypeCol: GridColDef<EncodeBiosample> = {
  field: "sampleType",
  headerName: "Sample Type",
  type: "singleSelect",
  valueOptions: ["tissue", "primary cell", "cell line", "in vitro differentiated cells", "organoid"],
  valueFormatter: (value) => value && capitalize(value),
};

export const lifeStageCol: GridColDef<EncodeBiosample> = {
  field: "lifeStage",
  headerName: "Life Stage",
  type: "singleSelect",
  valueOptions: ["adult", "embryonic"],
  valueFormatter: (value) => value && capitalize(value),
};

export const assaysCol: GridColDef<EncodeBiosample> = {
  field: "assays",
  headerName: "Assays",
  valueGetter: (_, row) => {
    const availableAssays = [];
    if (row.dnase_experiment_accession) availableAssays.push("DNase");
    if (row.atac_experiment_accession) availableAssays.push("ATAC");
    if (row.h3k4me3_experiment_accession) availableAssays.push("H3K4me3");
    if (row.h3k27ac_experiment_accession) availableAssays.push("H3K27ac");
    if (row.ctcf_experiment_accession) availableAssays.push("CTCF");
    return availableAssays.join(",");
  },
  sortComparator: (v1, v2) => {
    const count1 = v1.split(",").filter((s: string) => s.length > 0).length;
    const count2 = v2.split(",").filter((s: string) => s.length > 0).length;
    return count1 - count2;
  },
  renderCell: (params) => {
    if (params.rowNode.type === "group") return null;
    const row = params.row;
    return (
      <div onClick={(e) => e.stopPropagation()}>
        <AssayWheel
          row={{
            dnase: row.dnase_experiment_accession,
            atac: row.atac_experiment_accession,
            h3k4me3: row.h3k4me3_experiment_accession,
            h3k27ac: row.h3k27ac_experiment_accession,
            ctcf: row.ctcf_experiment_accession,
          }}
        />
      </div>
    );
  },
  groupable: false,
};

// -- Collection Column Helpers --

const collections = ["Core", "Partial", "Ancillary"] as const;

//Handles the two experiments that have unprocessed H3K4me3 samples which have "NA" values in file
//GM12866_ENCDO000ABQ & neural_crest_cell_ENCDO222AAA
const fileExists = (fileID: string | null): Boolean => {
  return !!fileID && fileID !== "NA"
}

const getCollectionForSample = (sample: EncodeBiosample): (typeof collections)[number] | null => {
  const filesAvailable: Record<CcreAssay, Boolean> = {
    dnase: fileExists(sample.dnase_file_accession),
    h3k4me3: fileExists(sample.h3k4me3_file_accession),
    h3k27ac: fileExists(sample.h3k27ac_file_accession),
    ctcf: fileExists(sample.ctcf_file_accession),
    atac: fileExists(sample.atac_file_accession),
  };
  if (!Object.values(filesAvailable).includes(true)) return null; // True for grouping rows and GM12866_ENCDO000ABQ
  let collection: (typeof collections)[number] = "Ancillary";
  if (filesAvailable.dnase) {
    collection = "Partial";
    if (filesAvailable.ctcf && filesAvailable.h3k4me3 && filesAvailable.h3k27ac) {
      collection = "Core";
    }
  }
  return collection;
};

// define this to properly sort grouping rows and GM12866_ENCDO000ABQ
const sortOrder = [...collections, null]

export const collectionCol: GridColDef<EncodeBiosample> = {
  field: "collection",
  headerName: "Collection",
  type: "singleSelect",
  valueOptions: [...collections],
  valueGetter: (_, row) => getCollectionForSample(row),
  renderCell: (params) => {
    const row = params.row
    if (
      (row.dnase_experiment_accession && !fileExists(row.dnase_file_accession)) ||
      (row.h3k4me3_experiment_accession && !fileExists(row.h3k4me3_file_accession)) ||
      (row.h3k27ac_experiment_accession && !fileExists(row.h3k27ac_file_accession)) ||
      (row.ctcf_experiment_accession && !fileExists(row.ctcf_file_accession))
    )
      return (
        <Tooltip title="This sample's H3K4me3 experiment data was not run through the ENCODE pipeline. This assay is ignored when placing this sample in its given collection">
          <Stack direction={"row"} alignItems={"center"}>
            {row.name === "GM12866_ENCDO000ABQ" ? "NA" : getCollectionForSample(row)}
            <InfoOutline fontSize="small" />
          </Stack>
        </Tooltip>
      );
    else return getCollectionForSample(row);
  },
  sortComparator: (v1, v2) => sortOrder.indexOf(v1) - sortOrder.indexOf(v2),
};

//ENCODE Experiment Accession (plain text)
export const dnaseExpCol: GridColDef<EncodeBiosample> = {
  field: "dnase_experiment_accession",
  headerName: "DNase Exp. ID",
  sortable: false,
  groupable: false,
};
export const h3k4me3ExpCol: GridColDef<EncodeBiosample> = {
  field: "h3k4me3_experiment_accession",
  headerName: "H3K4me3 Exp. ID",
  sortable: false,
  groupable: false,
};
export const h3k27acExpCol: GridColDef<EncodeBiosample> = {
  field: "h3k27ac_experiment_accession",
  headerName: "H3K27ac Exp. ID",
  sortable: false,
  groupable: false,
};
export const ctcfExpCol: GridColDef<EncodeBiosample> = {
  field: "ctcf_experiment_accession",
  headerName: "CTCF Exp. ID",
  sortable: false,
  groupable: false,
};
export const atacExpCol: GridColDef<EncodeBiosample> = {
  field: "atac_experiment_accession",
  headerName: "ATAC Exp. ID",
  sortable: false,
  groupable: false,
};

//ENCODE File ID (plain text)
export const dnaseFileIdCol: GridColDef<EncodeBiosample> = {
  field: "dnase_file_accession",
  headerName: "DNase File ID",
  sortable: false,
  groupable: false,
};
export const h3k4me3FileIdCol: GridColDef<EncodeBiosample> = {
  field: "h3k4me3_file_accession",
  headerName: "H3K4me3 File ID",
  sortable: false,
  groupable: false,
};
export const h3k27acFileIdCol: GridColDef<EncodeBiosample> = {
  field: "h3k27ac_file_accession",
  headerName: "H3K27ac File ID",
  sortable: false,
  groupable: false,
};
export const ctcfFileIdCol: GridColDef<EncodeBiosample> = {
  field: "ctcf_file_accession",
  headerName: "CTCF File ID",
  sortable: false,
  groupable: false,
};
export const atacFileIdCol: GridColDef<EncodeBiosample> = {
  field: "atac_file_accession",
  headerName: "ATAC File ID",
  sortable: false,
  groupable: false,
};

export const dnaseZscoreUrlCol: GridColDef<EncodeBiosample> = {
  field: "dnaseZ",
  headerName: "DNase Z-scores",
  valueGetter: (_, row) =>
    row.dnase_experiment_accession && row.dnase_file_accession
      ? `https://downloads.wenglab.org/Registry-V4/SCREEN/Signal-Files/${row.dnase_experiment_accession}-${row.dnase_file_accession}.tsv`
      : null,
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download DNase z-score by cCRE (.tsv) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="DNase"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const h3k4me3ZscoreUrlCol: GridColDef<EncodeBiosample> = {
  field: "h3k4me3Z",
  headerName: "H3K4me3 Z-scores",
  valueGetter: (_, row) =>
    //check if file exists to handle the two samples with unprocessed h3k4me3 experiments: GM12866_ENCDO000ABQ & neural_crest_cell_ENCDO222AAA
    row.h3k4me3_experiment_accession && fileExists(row.h3k4me3_file_accession)
      ? `https://downloads.wenglab.org/Registry-V4/SCREEN/Signal-Files/${row.h3k4me3_experiment_accession}-${row.h3k4me3_file_accession}.tsv`
      : null,
  renderCell: (params) => {
    if (["GM12866_ENCDO000ABQ", "neural_crest_cell_ENCDO222AAA"].includes(params.row.name))
      return (
        <DownloadButton
          disabled
          message={() =>
            "This sample's H3K4me3 experiment was not run through the ENCODE Pipeline and thus z-scores are not available"
          }
          url={params.value}
          displayName={params.row.displayname}
          assay="H3K4me3"
          ontology={params.row.ontology}
        />
      );
    else if (!(params.rowNode.type === "group") && params.value)
      return (
        <DownloadButton
          message={(fileSize) => `Download H3K4me3 z-score by cCRE (.tsv) - ${fileSize}`}
          url={params.value}
          displayName={params.row.displayname}
          assay="H3K4me3"
          ontology={params.row.ontology}
        />
      );
  },
  groupable: false,
  sortable: false,
};

export const h3k27acZscoreUrlCol: GridColDef<EncodeBiosample> = {
  field: "h3k27acZ",
  headerName: "H3K27ac Z-scores",
  valueGetter: (_, row) =>
    row.h3k27ac_experiment_accession && row.h3k27ac_file_accession
      ? `https://downloads.wenglab.org/Registry-V4/SCREEN/Signal-Files/${row.h3k27ac_experiment_accession}-${row.h3k27ac_file_accession}.tsv`
      : null,
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download H3K27ac z-score by cCRE (.tsv) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="H3K27ac"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const ctcfZscoreUrlCol: GridColDef<EncodeBiosample> = {
  field: "ctcfZ",
  headerName: "CTCF Z-scores",
  valueGetter: (_, row) =>
    row.ctcf_experiment_accession && row.ctcf_file_accession
      ? `https://downloads.wenglab.org/Registry-V4/SCREEN/Signal-Files/${row.ctcf_experiment_accession}-${row.ctcf_file_accession}.tsv`
      : null,
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download CTCF z-score by cCRE (.tsv) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="CTCF"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const atacZscoreUrlCol: GridColDef<EncodeBiosample> = {
  field: "atacZ",
  headerName: "ATAC Z-scores",
  valueGetter: (_, row) =>
    row.atac_experiment_accession && row.atac_file_accession
      ? `https://downloads.wenglab.org/Registry-V4/SCREEN/Signal-Files/${row.atac_experiment_accession}-${row.atac_file_accession}.tsv`
      : null,
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download ATAC z-score by cCRE (.tsv) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="ATAC"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const dnaseSignalUrlCol: GridColDef<EncodeBiosample> = {
  field: "dnase_signal_url",
  headerName: "DNase Signal",
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download DNase Signal (.bigWig) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="DNase"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const h3k4me3SignalUrlCol: GridColDef<EncodeBiosample> = {
  field: "h3k4me3_signal_url",
  headerName: "H3K4me3 Signal",
  valueGetter: (value, row) => (row.h3k4me3_file_accession === "NA" ? null : value),
  renderCell: (params) => {
    if (["GM12866_ENCDO000ABQ", "neural_crest_cell_ENCDO222AAA"].includes(params.row.name))
      return (
        <DownloadButton
          disabled
          message={() =>
            "This sample's H3K4me3 experiment was not run through the ENCODE Pipeline and thus the signal file is not available"
          }
          url={params.value}
          displayName={params.row.displayname}
          assay="H3K4me3"
          ontology={params.row.ontology}
        />
      );
    else if (!(params.rowNode.type === "group") && params.value)
      return (
        <DownloadButton
          message={(fileSize) => `Download H3K4me3 Signal (.bigWig) - ${fileSize}`}
          url={params.value}
          displayName={params.row.displayname}
          assay="H3K4me3"
          ontology={params.row.ontology}
        />
      );
  },
  groupable: false,
  sortable: false,
};

export const h3k27acSignalUrlCol: GridColDef<EncodeBiosample> = {
  field: "h3k27ac_signal_url",
  headerName: "H3K27ac Signal",
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download H3K27ac Signal (.bigWig) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="H3K27ac"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const ctcfSignalUrlCol: GridColDef<EncodeBiosample> = {
  field: "ctcf_signal_url",
  headerName: "CTCF Signal",
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download CTCF Signal (.bigWig) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="CTCF"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const atacSignalUrlCol: GridColDef<EncodeBiosample> = {
  field: "atac_signal_url",
  headerName: "ATAC Signal",
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download ATAC Signal (.bigWig) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="ATAC"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const chromHmmUrlCol: GridColDef<EncodeBiosample> = {
  field: "chromhmm_url",
  headerName: "ChromHMM States",
  renderCell: (params) =>
    params.rowNode.type !== "group" &&
    params.value && (
      <DownloadButton
        message={(fileSize) => `Download ChromHMM States (.bigBed) - ${fileSize}`}
        url={params.value}
        displayName={params.row.displayname}
        assay="ChromHMM"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const ccreBedUrlCol: GridColDef<EncodeBiosample> = {
  field: "bedurl",
  headerName: "cCREs (.bed)",
  align: "center",
  valueGetter: (_, row, __, apiRef) => {
    if (isAutogeneratedRow(row)) {
      const id = gridRowIdSelector(apiRef, row);
      const rowNode = gridRowNodeSelector(apiRef, id);
      const isGroupingByOntology = rowNode.type === "group" && rowNode.groupingField === "ontology";
      if (isGroupingByOntology && typeof rowNode.groupingKey === "string") {
        return getAvailableFiles(rowNode.groupingKey)
          .map((x) => `https://downloads.wenglab.org/${x.filename}`)
          .join(",");
      } else return null;
    }
    const signalIDs = [
      row.dnase_file_accession,
      row.h3k4me3_file_accession,
      row.h3k27ac_file_accession,
      row.ctcf_file_accession,
    ].filter((id) => id !== null && id !== undefined && id !== "NA");
    if (!signalIDs.length) return null // aka is ATAC-only
    return `https://downloads.wenglab.org/Registry-V4/${signalIDs.join("_")}.bed`;
  },
  renderCell: (params) => {
    if (params.rowNode.type === "group") {
      if (params.rowNode.groupingField === "ontology") {
        const ontology = (params.rowNode.groupingKey as string) ?? "";
        return <AggregateDownloadButton ontology={ontology} />;
      } else return null;
    }
    return (
      <DownloadButton
        message={(fileSize) =>
          params.value ? `Download cCREs (.bed) - ${fileSize}` : "cCREs only available for samples with DNase, H3K4me3, H3H27ac, and/or CTCF data"
        }
        url={params.value}
        disabled={!params.value} //aka is ATAC-only
        displayName={params.row.displayname}
        assay="cCREs"
        ontology={params.row.ontology}
      />
    );
  },
  groupable: false,
  sortable: false,
};

export const ccreBigBedUrlCol: GridColDef<EncodeBiosample> = {
  field: "bigbedurl",
  headerName: "cCREs (.bigBed)",
  align: 'center',
  valueGetter: (value: string, row) => {
    if (row.name === "GM12866_ENCDO000ABQ") return null //This sample has no cCREs file
    if (row.name === "neural_crest_cell_ENCDO222AAA") return value.replaceAll('_NA_', '_') //The url in file includes "NA" H3K4me3 file ID
    else return value
  },
  renderCell: (params) =>
    params.rowNode.type !== "group" && (
      <DownloadButton
        message={(fileSize) =>
          params.value ? `Download cCREs (.bigBed) - ${fileSize}` : "cCREs only available for samples with DNase, H3K4me3, H3H27ac, and/or CTCF data"
        }
        url={params.value}
        disabled={!params.value} //aka is ATAC-only
        displayName={params.row.displayname}
        assay="cCREs"
        ontology={params.row.ontology}
      />
    ),
  groupable: false,
  sortable: false,
};

export const rnaSeqCheckCol: GridColDef<EncodeBiosample> = {
  field: "rnaSeq",
  headerName: "Has RNA Seq",
  type: "boolean",
  valueGetter: (_, row) => (isAutogeneratedRow(row) ? null : !!row?.rna_seq_tracks?.length),
  renderCell: (params) => {
    if (params.value) {
      return <Check />;
    } else return null;
  },
};

export const columns: GridColDef<EncodeBiosample>[] = [
  displayNameCol,
  assaysCol,
  ontologyCol,
  sampleTypeCol,
  lifeStageCol,
  collectionCol,
  ccreBedUrlCol,
  ccreBigBedUrlCol,
  dnaseExpCol,
  dnaseFileIdCol,
  dnaseZscoreUrlCol,
  dnaseSignalUrlCol,
  atacExpCol,
  atacFileIdCol,
  atacZscoreUrlCol,
  atacSignalUrlCol,
  h3k4me3ExpCol,
  h3k4me3FileIdCol,
  h3k4me3ZscoreUrlCol,
  h3k4me3SignalUrlCol,
  h3k27acExpCol,
  h3k27acFileIdCol,
  h3k27acZscoreUrlCol,
  h3k27acSignalUrlCol,
  ctcfExpCol,
  ctcfFileIdCol,
  ctcfZscoreUrlCol,
  ctcfSignalUrlCol,
  chromHmmUrlCol,
  rnaSeqCheckCol,
];

/**
 * useful for resetting visible columns by spreading this then overriding with visible cols
 */
export const allColsHidden = {
  displayname: false,
  assays: false,
  ontology: false,
  sampleType: false,
  lifeStage: false,
  collection: false,
  bedurl: false,
  bigbedurl: false,
  dnase_experiment_accession: false,
  dnase_file_accession: false,
  dnaseZ: false,
  dnase_signal_url: false,
  atac_experiment_accession: false,
  atac_file_accession: false,
  atacZ: false,
  atac_signal_url: false,
  h3k4me3_experiment_accession: false,
  h3k4me3_file_accession: false,
  h3k4me3Z: false,
  h3k4me3_signal_url: false,
  h3k27ac_experiment_accession: false,
  h3k27ac_file_accession: false,
  h3k27acZ: false,
  h3k27ac_signal_url: false,
  ctcf_experiment_accession: false,
  ctcf_file_accession: false,
  ctcfZ: false,
  ctcf_signal_url: false,
  chromhmm_url: false,
  rnaSeq: false,
};
