import { GridRowId, TableProps } from "../Table";

export type EncodeBiosample = {
  name: string;
  ontology: string;
  lifeStage: string;
  sampleType: string;
  displayname: string;
  dnase_experiment_accession: string | null;
  h3k4me3_experiment_accession: string | null;
  h3k27ac_experiment_accession: string | null;
  ctcf_experiment_accession: string | null;
  atac_experiment_accession: string | null;
  dnase_file_accession: string | null;
  h3k4me3_file_accession: string | null;
  h3k27ac_file_accession: string | null;
  ctcf_file_accession: string | null;
  atac_file_accession: string | null;
  dnase_signal_url?: string;
  h3k4me3_signal_url?: string;
  h3k27ac_signal_url?: string;
  ctcf_signal_url?: string;
  atac_signal_url?: string;
  rna_seq_tracks?: {
    id: string;
    title: string;
    url: string;
    rnaseq_experiment_accession: string;
    rnaseq_file_accession: string;
  }[];
  chromhmm?: string;
  chromhmm_url?: string;
  bigbedurl?: string | null;
};

export interface BiosampleTableProps<T extends TableProps["rows"] = EncodeBiosample[]> extends Omit<
  TableProps,
  "rows" | "columns"
> {
  /**
   * assembly to fetch samples for (required)
   */
  assembly: "GRCh38" | "mm10";
  /**
   * If passing rows, no biosamples will be fetched inside the component. Must use useEncodeBiosampleData to retrieve and pass in
   */
  rows?: T;
  /**
   * Optionally override columns
   */
  columns?: TableProps["columns"];
  /**
   * optionally prefilter biosamples. Filters the rows before going into the table. To modify initial filter state of table use initialState
   */
  prefilterBiosamples?: (biosample: T extends object ? T[number] : undefined) => boolean;
  /**
   * Callback triggered when rowSelectionModel changes. Returns whole row objects. If only id needed, can use onRowSelectionModelChange
   */
  onSelectionChange?: (selected: EncodeBiosample[]) => void;
  /**
   * For controlled selection of biosamples in the table. Useful over rowSelectionModel since this does not require passing autogenerated row IDs
   */
  selected?: GridRowId[];
  /**
   * Callback triggered when a download is initiated. Receives the URL and a descriptive name for tracking purposes.
   */
  onDownload?: (url: string, name: string) => void;
}

const CCRE_ASSAYS = ["dnase", "atac", "h3k4me3", "h3k27ac", "ctcf"] as const;

export type CcreAssay = (typeof CCRE_ASSAYS)[number];
